'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync(require('node:path').join(__dirname,'../web/employee-keywords.js'),'utf8');
function harness(){const nodes=new Map(),handlers=[];const context=vm.createContext({Map,Set,URLSearchParams,Event:function(){},state:{view:'categories',products:[],skus:{selected:['S1']}},render:()=>{},document:{querySelector:()=>null,addEventListener:(type,fn)=>handlers.push({type,fn})},$:selector=>nodes.get(selector)||(selector==='#main'?{children:[]}:null),esc:value=>String(value).replace(/</g,'&lt;'),title:()=>'',renderCollectedProducts:()=>'',flowStep:()=>'keywords',json:(method,body)=>({method,body:JSON.stringify(body)}),activate:()=>{},notice:()=>{},confirm:()=>true,api:async()=>({items:[],total:0,categories:[]})});vm.runInContext(code,context);return{context,nodes,handlers}}
test('listing becomes default and library has no Seerfar API join',()=>{const h=harness();assert.equal(h.context.state.view,'listing');assert.equal(code.includes('/api/research/'),false);assert.equal(h.context.keywordLibraryPickerHtml().includes('搜索 / 刷新'),true)});
test('library selection is draft-only, preserving phrase order',async()=>{const h=harness();vm.runInContext("employeeKeywords.items=[{id:'k1',text:'кастрюля чугунная',category:'厨具',note:'测试'}]",h.context);const input={value:'',dispatchEvent(){this.changed=true}};h.nodes.set('#productPrimary',input);let writes=0;h.context.api=async()=>{writes++;return{}};const button={dataset:{keywordAction:'primary',id:'k1'}};await h.handlers.find(x=>x.type==='click').fn({target:{closest:()=>button}});assert.equal(input.value,'кастрюля чугунная');assert.equal(input.changed,true);assert.equal(writes,0)});
test('late filter results cannot replace a newer query',async()=>{const h=harness(),waiting=[];vm.runInContext('employeeKeywords.loaded=true',h.context);h.context.api=()=>new Promise(resolve=>waiting.push(resolve));const first=h.context.loadEmployeeKeywords(),second=h.context.loadEmployeeKeywords();waiting[1]({items:[{id:'new'}],total:1,categories:['新']});await second;waiting[0]({items:[{id:'old'}],total:1,categories:['旧']});await first;assert.equal(vm.runInContext('employeeKeywords.items[0].id',h.context),'new')});

test('first identity GET is serialized and submit cannot create another owner',async()=>{const h=harness(),waiting=[];h.context.api=()=>new Promise(resolve=>waiting.push(resolve));const first=h.context.loadEmployeeKeywords(),second=h.context.loadEmployeeKeywords();assert.equal(waiting.length,1);await h.handlers.find(x=>x.type==='submit').fn({target:{id:'employeeKeywordForm'},preventDefault(){}});assert.equal(waiting.length,1);waiting[0]({items:[],categories:[]});await Promise.all([first,second]);assert.equal(vm.runInContext('employeeKeywords.loaded',h.context),true)});

test('save locks edit and cancel until its snapshotted draft completes',async()=>{const h=harness(),waiting=[];vm.runInContext("employeeKeywords.loaded=true;employeeKeywords.edit='k1';employeeKeywords.draft={category:'锅',text:'cast',note:'old'};employeeKeywords.items=[{id:'k2',category:'碗',text:'new'}]",h.context);let sent;h.context.api=(path,options)=>{if(options){sent=options;return new Promise(resolve=>waiting.push(resolve))}return Promise.resolve({items:[],categories:[]})};const submit=h.handlers.find(x=>x.type==='submit').fn({target:{id:'employeeKeywordForm'},preventDefault(){}});const click=h.handlers.find(x=>x.type==='click').fn;for(const action of ['edit','cancel'])await click({target:{closest:()=>({dataset:{keywordAction:action,id:'k2'}})}});assert.equal(vm.runInContext('employeeKeywords.edit',h.context),'k1');assert.equal(JSON.parse(sent.body).note,'old');waiting[0]({});await submit;assert.equal(vm.runInContext('employeeKeywords.saving',h.context),false)});
