"""商品状态机与批次骨架（M1 地基，与模型层无关）。"""

from .steps import (
    MAX_SELECTED_SKUS,
    PHASE_A_STEPS,
    PHASE_B_STEPS,
    PIPELINE_STEPS,
    STEP_DEFINITIONS,
    STEP_LABELS_ZH,
    STEP_STATUS,
    ordered,
)
from .status import (
    ATTENTION_STATES,
    REMOTE_STATES,
    SCHEMA_VERSION,
    STATUS_ENUM,
    TERMINAL_STATES,
    complete_step,
    freeze_sku_run_snapshot,
    load_status,
    mark_needs_attention,
    maybe_create_operator_question,
    new_status,
    normalize,
    product_dir,
    queue_product,
    save_status,
    source_snapshot_binding,
    validate_status,
)
from .batch import BATCH_TERMINAL_STATES, create_batch

__all__ = [
    "MAX_SELECTED_SKUS",
    "PHASE_A_STEPS",
    "PHASE_B_STEPS",
    "PIPELINE_STEPS",
    "STEP_DEFINITIONS",
    "STEP_LABELS_ZH",
    "STEP_STATUS",
    "ordered",
    "ATTENTION_STATES",
    "REMOTE_STATES",
    "SCHEMA_VERSION",
    "STATUS_ENUM",
    "TERMINAL_STATES",
    "complete_step",
    "freeze_sku_run_snapshot",
    "load_status",
    "mark_needs_attention",
    "maybe_create_operator_question",
    "new_status",
    "normalize",
    "product_dir",
    "queue_product",
    "save_status",
    "source_snapshot_binding",
    "validate_status",
    "BATCH_TERMINAL_STATES",
    "create_batch",
]
